created all tables
Processed 0 rows
Traceback (most recent call last):
  File "populate_lore_db_in_bach.py", line 34, in <module>
    migrator.read_executions_in_batch(args.start, args.size)
  File "/host/home/yjiao/qaas/qaas-web/lore/backend/model_accessor.py", line 102, in read_executions_in_batch
    current_execution = Execution(self)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/state.py", line 482, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/host/home/yjiao/qaas/qaas-web/lore/backend/model.py", line 151, in __init__
    self.accept(initializer)
  File "/host/home/yjiao/qaas/qaas-web/lore/backend/model.py", line 157, in accept
    accessor.visitExecution(self)
  File "/host/home/yjiao/qaas/qaas-web/lore/backend/model_accessor.py", line 275, in visitExecution
    orig_src_loop = SrcLoop.get_src_loop_by_id(self, found_id)
  File "/host/home/yjiao/qaas/qaas-web/lore/backend/model.py", line 556, in get_src_loop_by_id
    res = session.query(SrcLoop).filter_by(table_id=id).one()
AttributeError: 'LoreMigrator' object has no attribute 'query'
